export type Development = { date: string; headline: string; summary: string; source: string; publisher: string; kind: "announcement" | "filing" | "deployment evidence" };
export type CompanyProfile = { slug: string; name: string; service: string; approach: string; partnerships: string; source: string; developments: Development[] };

export const profiles: Record<string, Omit<CompanyProfile,"slug"|"name">> = {
  "Waymo": { service: "Driverless passenger ridehail in selected U.S. markets.", approach: "Geofenced commercial robotaxi service with market-specific operating areas.", partnerships: "Uber distributes Waymo rides in Austin and Atlanta.", source: "https://waymo.com/waymo-on-uber/", developments: [{ date: "2026-05", headline: "Waymo rides available through Uber in Austin and Atlanta", summary: "The two companies describe the market-specific Waymo-on-Uber offering.", source: "https://waymo.com/waymo-on-uber/", publisher: "Waymo", kind: "announcement" }] },
  "Aurora": { service: "Commercial autonomous long-haul trucking.", approach: "Aurora Driver operates on selected freight corridors, with truck-platform integrations.", partnerships: "Aurora names FedEx, Uber Freight, Volvo Autonomous Solutions, and others as commercial or technology collaborators.", source: "https://ir.aurora.tech/", developments: [{ date: "2026-07-22", headline: "Aurora launches second-generation driverless trucks", summary: "Aurora describes the updated commercial hardware fleet and customer rollout.", source: "https://ir.aurora.tech/news-events/press-releases/detail/144/aurora-launches-second-generation-driverless-trucks-in-u-s-to-meet-customer-demand", publisher: "Aurora", kind: "announcement" }] },
  "May Mobility": { service: "Autonomous passenger rides and shuttle-style service.", approach: "Deploys its driving system with local service partners in selected markets.", partnerships: "The company names Lyft, Uber, Toyota, NTT, and Grab; some announced services are planned rather than live.", source: "https://maymobility.com/posts/may-mobility-first-publicly-listed-pure-play-autonomous-ride-hail-technology-company-acp-holdings-acquisition-corp/", developments: [] },
  "Gatik": { service: "Middle-mile autonomous freight for retail and distribution routes.", approach: "Uses box trucks on repeatable, selected logistics routes.", partnerships: "Gatik describes customer work with Walmart and technology or vehicle collaborations with NVIDIA and Isuzu.", source: "https://archive.gatik.ai/news/press-releases/gatik-collaboration-with-nvidia/", developments: [{ date: "2026-01-27", headline: "Gatik reports scaled driverless commercial deliveries", summary: "Company announcement on expanded freight operations and its vehicle program.", source: "https://archive.gatik.ai/news/press-releases/gatik-becomes-first-us-company-to-operate-fully-driverless-trucks-at-scale-for-commercial-deliveries/", publisher: "Gatik", kind: "announcement" }] },
  "Zoox": { service: "Passenger robotaxi service in limited markets.", approach: "Uses a purpose-built bidirectional vehicle and staged market rollout.", partnerships: "No operating partner is identified in this profile yet.", source: "https://zoox.com/community/", developments: [] },
};

const modeLabel: Record<string,string> = { ridehail: "Passenger ridehail", shuttle: "Passenger shuttle", freight: "Freight transport", passenger: "Passenger service" };
export function companySlug(name: string) { return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
export function buildProfiles(locations: {company:string; mode:string; market:string; state:string; source_url:string; source_date?:string}[]): CompanyProfile[] {
  const groups = new Map<string, typeof locations>();
  for (const row of locations) groups.set(row.company, [...(groups.get(row.company) ?? []), row]);
  return Array.from(groups, ([name, rows]) => {
    const modes = Array.from(new Set(rows.map(r => modeLabel[r.mode] ?? r.mode))).join(" and ").toLowerCase();
    const c = profiles[name];
    const evidence = Array.from(new Map(rows.filter(r => r.source_url && r.source_date).map(r => [`${r.source_url}|${r.market}`, r])).values()).map(r => ({
      date: r.source_date!, headline: `Deployment evidence: ${r.market}, ${r.state}`, summary: `The Observatory records ${name}'s ${r.mode} activity in this market, based on the linked source. The date is the source or verification date, not necessarily the service launch date.`, source: r.source_url, publisher: "Operating record", kind: "deployment evidence" as const,
    }));
    return { slug: companySlug(name), name, service: c?.service ?? `${modes.charAt(0).toUpperCase()+modes.slice(1)} documented in the Observatory's current U.S. deployment records.`, approach: c?.approach ?? "Service geography and operating conditions vary by market; examine the linked deployment evidence for scope.", partnerships: c?.partnerships ?? "Partnerships have not yet been independently documented in this profile.", source: c?.source ?? rows.find(r => r.source_url)?.source_url ?? "", developments: [...(c?.developments ?? []), ...evidence] };
  }).sort((a,b) => a.name.localeCompare(b.name));
}
