import type { PolicyBrief } from "./statePolicy";

// Policy snapshots paraphrased from Baker Donelson's 50-state guide (updated Aug. 4, 2026).
// These summarize the framework, not a legal determination of any operator's authorization.
const guide = { label: "2026 state-by-state AV statute and regulation guide", url: "https://www.bakerdonelson.com/avmap" };
const legislation = { label: "NCSL AV legislation database", url: "https://www.ncsl.org/transportation/autonomous-vehicles-legislation-database" };
const rows: Record<string, [string, string, string]> = {
  AL: ["Commercial vehicles only", "Alabama's AV-specific statute governs automated commercial vehicles. Its scope does not establish a general passenger robotaxi pathway.", "Alabama DOT has state-level jurisdiction under the commercial vehicle framework."],
  AK: ["No enacted AV operation framework identified", "Proposals to restrict autonomous operation and assign operator liability remained under consideration in the 2026 survey. Proposed bills are not current operating authority.", "General motor vehicle law applies while the proposed AV measures remain unenacted."],
  AR: ["Driverless operation with submissions", "Arkansas permits driverless operation when statutory conditions and advance submissions, including commercial-purpose information, are satisfied.", "State submission and applicable traffic and vehicle rules."],
  CO: ["AV operating framework; truck restrictions vetoed", "Colorado has an AV statute, while proposed in-vehicle human requirements for automated commercial trucks were vetoed in both 2025 and 2026. A vetoed bill cannot be treated as a current restriction.", "State motor vehicle law and any applicable testing conditions."],
  CT: ["Municipal pilot program", "Connecticut's dedicated AV pathway centers on a limited pilot involving selected municipalities. A pilot law is not blanket authority for commercial deployment statewide.", "Pilot approval and participating municipalities."],
  DE: ["No enacted AV-specific operating statute identified", "Delaware's 2025 proposal to require an onboard operator failed. Its AV advisory activity does not itself grant a commercial permit.", "Ordinary vehicle rules; no distinct statewide commercial AV permit identified in the guide."],
  DC: ["Testing pathway", "The District retained AV testing provisions after repealing a broader permission to operate. A test authorization should be distinguished from passenger-service deployment.", "District testing rules and any applicable local transportation authority."],
  HI: ["Executive-order coordination", "Hawaii established a government contact and interagency support for AV testing; the 2026 proposal requiring an onboard commercial passenger operator did not pass.", "General vehicle law and agency coordination rather than a documented broad AV deployment permit."],
  ID: ["Planning and agency coordination", "Idaho's executive-order committee examined testing and deployment issues. The 2026 survey identified no enacted AV-specific operating statute.", "General motor vehicle requirements and agency guidance."],
  IL: ["State preemption of local prohibitions", "Illinois law limits local governments' ability to prohibit AVs, but that rule alone does not establish a statewide permit or demonstrate an active commercial service.", "State vehicle and traffic law; local powers are constrained by statute."],
  IN: ["No enacted AV-specific operating statute identified", "Indiana's 2025 bill addressing autonomous tractor-trailers failed. The 2026 survey did not identify a dedicated AV operating law.", "Ordinary vehicle and commercial-carrier requirements."],
  IA: ["Statutory operating pathway", "Iowa's statute addresses operation of automated driving systems. Multiple proposed 2026 changes failed, so those proposals should not be counted as current conditions.", "State traffic and vehicle requirements under Iowa's AV statute."],
  KS: ["Private and commercial operation pathway", "Kansas law accommodates private and commercial AV operation subject to statutory conditions. This permission says nothing about a particular company's ODD.", "State vehicle and traffic rules."],
  KY: ["Operating statute with freight transition", "Kentucky's AV framework took effect in 2024. The survey reports that a temporary onboard-driver rule for very heavy commercial vehicles expired in August 2026 after an extension failed.", "State vehicle law and any remaining commercial-carrier requirements."],
  LA: ["Commercial AV framework", "Louisiana's dedicated AV operating provisions focus on commercial uses. Passenger service cannot be inferred from that freight-oriented authority.", "State commercial-vehicle and traffic requirements."],
  ME: ["Pilot authority", "Maine authorizes transportation officials to establish AV pilot activity. The guide does not describe a broad commercial robotaxi approval regime.", "Maine DOT pilot rules and general vehicle requirements."],
  MD: ["Narrow converted-vehicle provisions", "Maryland's AV-specific statute focuses on converted vehicles for commercial or industrial use. Broader 2025 operation and safety-operator bills did not pass.", "Motor Vehicle Administration and applicable vehicle law."],
  MI: ["Research, testing, and SAVE projects", "Michigan's statutes emphasize AV research and testing, including manufacturer-linked SAVE projects. A testing program does not by itself establish open commercial ridehail authorization.", "State testing and project-specific requirements."],
  MN: ["No comprehensive AV operation law enacted", "Minnesota proposed an AV and on-demand network framework in 2026, but it failed. The proposal should not be represented as an active permit system.", "General vehicle rules and any relevant agency guidance."],
  MS: ["General driverless operating pathway", "Mississippi allows a person to operate an AV when statutory conditions are met. The permission is broader than a manufacturer-only test program.", "State traffic, registration, and safety requirements."],
  MO: ["No dedicated operating framework enacted", "A Missouri proposal requiring an active human driver was still pending in the survey. Its introduction alone does not change current AV operating law.", "General state motor vehicle and carrier rules."],
  MT: ["Automated-vehicle and platooning provisions", "Montana enacted measures addressing automated vehicles and platooning in 2025. The exact authority for a proposed passenger or freight service requires examination of the relevant provisions.", "State vehicle and commercial-carrier requirements."],
  NE: ["Conditional driverless operation", "Nebraska permits ADS-equipped vehicles with an onboard licensed driver and provides a conditional pathway for operation without one.", "State statutory requirements for driverless operation and ordinary vehicle law."],
  NH: ["Advisory commission and testing pilot", "New Hampshire provides a testing pilot and an AV advisory commission. Those provisions do not establish general commercial deployment statewide.", "Pilot approval and commission reporting."],
  NJ: ["Proposed pilot, not enacted", "A 2026 bill proposed a fully autonomous vehicle pilot. The guide identifies it as pending, so a proposed pilot cannot be shown as active authorization.", "General motor vehicle rules pending enacted AV legislation."],
  NM: ["Notified testing pathway", "New Mexico's AV framework addresses testing and requires advance notification. A testing notice is distinct from commercial deployment approval.", "State transportation and testing-notification requirements."],
  NC: ["Operation statute and policy committee", "North Carolina has AV-specific operating provisions and a committee charged with recommendations for testing and deployment. A statewide law does not reveal a company's actual service area.", "State traffic law and committee-led policy review."],
  ND: ["Conditional AV operation", "North Dakota permits autonomous operation subject to applicable state and federal law. A 2025 AV funding proposal failed.", "Ordinary vehicle law plus the state's AV operating provision."],
  OH: ["Executive-order testing registration", "Ohio's DriveOhio program requires companies to register before AV testing. The guide identifies no general AV operation statute; registration should not be read as commercial deployment approval.", "DriveOhio testing registration and state vehicle rules."],
  OK: ["Conditional operating pathway", "Oklahoma permits AV operation when statutory conditions and ordinary registration rules are satisfied; on-demand networks also remain subject to applicable service law.", "State traffic, registration, and on-demand network requirements."],
  OR: ["Task force, no general operating law", "Oregon established an AV task force. A 2026 proposal to permit operation without ordinary driving privileges failed.", "General vehicle law while broader AV operation proposals remain unenacted."],
  PA: ["Self-certification under PennDOT", "Pennsylvania's AV pathway places oversight with PennDOT and requires self-certification. A separate 2025 certificate proposal was pending in the survey.", "PennDOT self-certification and state traffic requirements."],
  RI: ["No dedicated AV operating law identified", "The 2026 survey identifies no AV-specific statute or new proposal. That does not establish that an individual deployment is authorized.", "General motor vehicle and service rules."],
  SC: ["No dedicated AV operating law identified", "South Carolina's survey entry identifies no new AV legislation since 2018. Operator status still depends on general vehicle law and any service-specific rules.", "General state motor vehicle requirements."],
  SD: ["AV operation and platooning laws", "South Dakota added an AV operating statute in 2024 alongside earlier platooning provisions. Commercial freight and passenger services should be assessed under their relevant requirements.", "State AV, commercial-carrier, and traffic rules."],
  TN: ["Automated Vehicles Act", "Tennessee has a general AV operating framework. A 2026 amendment addresses traffic violations committed by AVs, adding a distinct accountability issue to the state's policy picture.", "State traffic law and the Automated Vehicles Act."],
  UT: ["Statutory AV operation", "Utah's AV law governs operation of ADS-equipped vehicles subject to state and federal requirements. A 2026 information-request bill failed.", "State AV statute and ordinary traffic requirements."],
  VT: ["Restrictive testing authorization", "Vermont's AV law addresses testing only, with public comment and an onboard human driver for each approved test. It is not a general driverless passenger-service pathway.", "Test-specific approval and public-comment process."],
  VA: ["Proposed licensing, not enacted", "Virginia considered autonomous operation licenses in SB 670, but the measure was continued to 2027 in the survey. Its proposed licenses are not existing permits.", "General vehicle law pending any enacted AV-specific licensing framework."],
  WV: ["Personal, commercial, and network operation", "West Virginia's AV law accommodates several service types subject to conditions. Driverless operators must submit a law-enforcement interaction plan before operating.", "State vehicle rules and law-enforcement interaction plan."],
  WI: ["Executive-order coordination", "Wisconsin's AV steering committee addressed testing and deployment policy. Proposed 2026 board and permit legislation failed, leaving no such new permit in force.", "General vehicle rules and existing agency coordination."],
  WY: ["No dedicated AV statute identified", "The 2026 guide identifies no AV-specific operating law or new proposal in Wyoming. That finding does not amount to a positive authorization for any proposed service.", "General motor vehicle and commercial-carrier rules."],
};
export const surveyBriefs: Record<string, PolicyBrief> = Object.fromEntries(Object.entries(rows).map(([state, [framework, analysis, oversight]]) => [state, {
  framework, analysis, oversight, sources: [guide, legislation], reviewed: "Guide updated August 2026",
}]));
