import sf from "../../../public/data/av_311_complaints.json";
import austin from "../../../public/data/austin_av_reports.json";
import coverage from "../../../public/data/av_311_source_registry.json";
import context from "../../../public/data/sf_311_waymo_s2_context.json";

const base = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const sfTypes = Object.entries(sf.records.reduce((counts: Record<string, number>, row) => {
  const label = row.type === "incident_report" ? "Incident Report" : row.type === "general_complaint" ? "General Complaint" : "Other Feedback";
  counts[label] = (counts[label] ?? 0) + 1;
  return counts;
}, {})).sort((a,b) => b[1]-a[1]);
const feedback = austin.records.filter(row => row.reporter_type.toLowerCase() === "resident feedback");
const staffReports = austin.records.filter(row => row.reporter_type.toLowerCase() !== "resident feedback");
const issueMix = [...new Set(austin.records.map(row => row.issue))].map(issue => ({issue, resident:feedback.filter(r=>r.issue===issue).length, other:staffReports.filter(r=>r.issue===issue).length})).sort((a,b)=>(b.resident+b.other)-(a.resident+a.other));

type Row = { label: string; value: number };
function Bars({ rows, color = "#2c76bf" }: { rows: Row[]; color?: string }) {
  const max = Math.max(1, ...rows.map(r => r.value));
  return <div className="grid gap-3 mt-5">{rows.map(row => <div key={row.label} className="grid grid-cols-[minmax(115px,1fr)_minmax(80px,2fr)_42px] gap-3 items-center text-sm">
    <span className="leading-snug">{row.label}</span><div className="h-3.5 rounded-sm bg-[#e8eef4]"><div className="h-3.5 rounded-sm" style={{ backgroundColor: color, width: `${100 * row.value / max}%` }} /></div><strong className="text-right tabular-nums">{row.value}</strong>
  </div>)}</div>;
}
function Months({rows, keyName, color="#2c76bf"}: {rows: {month:string; [key:string]: number|string}[]; keyName:string; color?:string}) {
  const series = rows.slice(-12).map(r=>({month:r.month,value:Number(r[keyName])}));
  const max=Math.max(1,...series.map(r=>r.value));
  const coords=series.map((r,i)=>({x:44+i* (612/Math.max(1,series.length-1)), y:148-r.value/max*118}));
  return <div className="mt-4"><svg viewBox="0 0 700 195" role="img" aria-label={`Monthly series: ${series.map(r=>`${r.month}: ${r.value}`).join(', ')}`} className="w-full h-auto"><path d="M44 148H656" stroke="#d4dfe9" fill="none"/><path d="M44 30H656" stroke="#eef2f5" fill="none"/><text x="4" y="35" fontSize="13" fill="#536477">{max}</text><text x="25" y="151" fontSize="13" fill="#536477">0</text><polyline fill="none" stroke={color} strokeWidth="3" strokeLinejoin="round" points={coords.map(p=>`${p.x},${p.y}`).join(' ')}/>{coords.map((p,i)=><g key={series[i].month}><circle cx={p.x} cy={p.y} r="4" fill={color}><title>{series[i].month}: {series[i].value}</title></circle>{(i===0||i===series.length-1||i%3===0)&&<text x={p.x} y="177" textAnchor="middle" fontSize="12" fill="#536477">{series[i].month.slice(2)}</text>}</g>)}</svg><p className="text-sm text-neutral-600">{series[0]?.month} to {series.at(-1)?.month} · {series.reduce((a,r)=>a+r.value,0).toLocaleString()} reports</p></div>;
}
export default function ComplaintsPage() {
  return <main className="max-w-6xl px-5 sm:px-8 py-8"><p className="eyebrow">Reporting / City Records</p><h1 className="text-4xl font-semibold text-[#0b1d33] mt-2">Citizen Complaints</h1>
    <p className="text-base leading-relaxed text-neutral-600 mt-3 max-w-4xl">Two cities publish AV-identifiable resident reports: San Francisco’s dedicated 311 category and Austin’s city-compiled <em>Resident Feedback</em>. Select a city section for its own issue and time breakdown. These sources use different intake systems and cannot be compared as complaint rates.</p>
    <div className="grid sm:grid-cols-2 gap-3 mt-6"><a href="#san-francisco" className="viz-card p-5 block hover:border-[#2c76bf]"><p className="text-sm text-neutral-600">San Francisco · AV 311 Requests</p><strong className="block text-3xl text-[#123b69] mt-2">{sf.total_records.toLocaleString()}</strong><span className="text-sm text-[#184f95] underline">Explore SF 311 →</span></a><a href="#austin" className="viz-card p-5 block hover:border-[#ab6a3b]"><p className="text-sm text-neutral-600">Austin · Resident Feedback</p><strong className="block text-3xl text-[#123b69] mt-2">{austin.resident_feedback_count.toLocaleString()}</strong><span className="text-sm text-[#184f95] underline">Explore Austin reports →</span></a></div>
    <section id="san-francisco" className="mt-9 scroll-mt-6"><div className="flex flex-wrap justify-between items-end gap-3"><div><p className="eyebrow">San Francisco</p><h2 className="text-2xl font-semibold">311 Autonomous Vehicle Complaints</h2></div><a href={sf.source_url} className="text-sm text-[#184f95] underline">Official Dataset ↗</a></div>
      <p className="text-sm text-neutral-600 mt-2 max-w-4xl">Records exactly matching the city’s “Autonomous Vehicle Complaints” service category, since April 2025. Published subtypes classify the submission; the public data do not identify the operator or a detailed behavioral issue. “Incident Report” is a 311 label, not a verified collision.</p>
      <div className="grid lg:grid-cols-2 gap-3 mt-4"><div className="viz-card p-5"><h3 className="text-lg font-semibold">City Complaint Type</h3><p className="text-sm text-neutral-600">SF311 service subtype · all indexed requests</p><Bars rows={sfTypes.map(([label,value])=>({label,value}))} /></div><div className="viz-card p-5"><h3 className="text-lg font-semibold">Requests by Month</h3><p className="text-sm text-neutral-600">Most recent 12 published months · SF311 only</p><Months rows={sf.monthly} keyName="complaints" /></div></div>
      <div className="viz-card p-5 mt-3"><h3 className="text-lg font-semibold">What the Public Records Can Tell Us</h3><p className="text-sm text-neutral-600 mt-2">These vehicles use public curb and travel lanes. Parking, double parking, bike and bus lane obstruction, blocked traffic, and stand offs are useful questions for oversight. This SF311 export does not code those behaviors or name the vehicle operator, so its subtype counts cannot answer them. The chart above counts requests, not confirmed violations. We will add issue breakdowns when a public, linkable source identifies the behavior in individual records.</p></div>
      <div className="viz-card p-5 mt-3"><h3 className="text-lg font-semibold">SF Requests and Waymo Street Exposure</h3><p className="text-sm text-neutral-600 mt-1">Matched quarter: January–March 2026 · San Francisco county S2 cells</p><div className="grid sm:grid-cols-3 gap-4 mt-4"><div><strong className="text-2xl text-[#123b69]">{context.sf_311_requests_all_operators}</strong><p className="text-sm">SF311 AV requests · all operators</p></div><div><strong className="text-2xl text-[#123b69]">{(context.waymo_ro_miles_sf_county/1e6).toFixed(2)}M</strong><p className="text-sm">Waymo rider only miles · SF county</p></div><div><strong className="text-2xl text-[#123b69]">{context.sf_311_requests_per_million_waymo_ro_miles_context_only}</strong><p className="text-sm">All AV requests per million Waymo miles · context only</p></div></div><p className="text-sm text-neutral-600 mt-4">The numerator includes all AV operators; the denominator includes only Waymo. This mixed-source ratio is a measure of public reporting alongside Waymo street exposure, <strong>not</strong> a Waymo complaint rate or a measure of violations. In the twelve months through March 2026, SF311 recorded {context.sf_311_requests_prior_twelve_months} AV requests. An annual SF-county S2 baseline is unavailable in the archived files, so no annual per-mile rate is shown. <a href={`${base}/data/sf_311_waymo_s2_context.json`} className="underline text-[#184f95]">Method and data ↗</a></p></div>
      <details className="viz-card p-5 mt-3"><summary className="cursor-pointer font-semibold text-[#184f95]">Recent SF Requests ({sf.total_records.toLocaleString()} total)</summary><div className="grid gap-2 mt-4">{[...sf.records].reverse().slice(0,20).map(row=><div key={row.id} className="text-sm border-t border-[#e1e7ee] pt-2 flex justify-between gap-4"><span>{row.requested_date} · {row.type.replaceAll("_"," ")} · {row.status}</span><a href={row.source_url} className="text-[#184f95] underline whitespace-nowrap">{row.id} ↗</a></div>)}</div></details>
      <p className="text-sm text-neutral-600 mt-3">{sf.limitations} Last source update: {sf.source_data_as_of.slice(0,10)}.</p>
    </section>
    <section id="austin" className="mt-10 scroll-mt-6"><div className="flex flex-wrap justify-between items-end gap-3"><div><p className="eyebrow">Austin</p><h2 className="text-2xl font-semibold">Resident Feedback on AVs</h2></div><a href={austin.dashboard_url} className="text-sm text-[#184f95] underline">Official City Dashboard ↗</a></div>
      <p className="text-sm text-neutral-600 mt-2 max-w-4xl">Austin Transportation and Public Works publishes {austin.total_city_reports} substantive AV reports. {austin.resident_feedback_count} are labeled “Resident Feedback”; these are the only records counted here as citizen reports. The remaining {austin.total_city_reports-austin.resident_feedback_count} include police, fire, school police, EMS, and other city reports. The source also contains {austin.blank_source_rows_excluded} empty placeholder, excluded from the totals. The city says its log draws partly from 311; it does not say that every resident entry came through 311.</p>
      <div className="grid lg:grid-cols-2 gap-3 mt-4"><div className="viz-card p-5"><h3 className="text-lg font-semibold">Reported Issue</h3><p className="text-sm text-neutral-600">Resident Feedback only · city-defined categories</p><Bars rows={austin.resident_issues.map(r=>({label:r.issue,value:r.resident_feedback}))} color="#bd7140" /></div><div className="viz-card p-5"><h3 className="text-lg font-semibold">Resident Feedback by Month</h3><p className="text-sm text-neutral-600">Most recent 12 months with feedback · Austin residents only</p><Months rows={austin.monthly} keyName="resident_feedback" color="#bd7140" /></div></div>
      <div className="viz-card p-5 mt-3"><h3 className="text-lg font-semibold">Public Right of Way</h3><p className="text-sm text-neutral-600 mt-2">Austin labels {feedback.filter(r=>r.issue==="Blocking Traffic").length} resident reports “Blocking Traffic” and {staffReports.filter(r=>r.issue==="Blocking Traffic").length} other city reports that way. Its broader “Nuisance” category covers {feedback.filter(r=>r.issue==="Nuisance").length} resident reports. Together these flags show where AV operation affects shared streets, but they do not independently establish double parking, bike or bus lane obstruction, or an unsafe stop. “Near Miss” and “Safety Concern” are also allegations, not adjudicated findings. The issue matrix below keeps resident and department reports separate.</p></div>
      <div className="viz-card p-5 mt-3"><h3 className="text-lg font-semibold">How Reports Differ by Source</h3><p className="text-sm text-neutral-600 mt-1">City issue categories across all {austin.total_city_reports} substantive reports. Resident Feedback and other city sources are counted separately.</p><div className="flex flex-wrap gap-5 text-sm mt-3"><span><span className="inline-block w-3 h-3 rounded-sm bg-[#bd7140] mr-1"/>Resident Feedback ({feedback.length})</span><span><span className="inline-block w-3 h-3 rounded-sm bg-[#71859d] mr-1"/>Other City Sources ({staffReports.length})</span></div><div className="grid gap-3 mt-5">{issueMix.map(row=><div key={row.issue} className="grid sm:grid-cols-[190px_minmax(0,1fr)_90px] gap-2 items-center text-sm"><span className="font-medium">{row.issue}</span><div className="flex h-4 bg-[#e8eef4] overflow-hidden rounded-sm"><div style={{width:`${row.resident/Math.max(1,issueMix[0].resident+issueMix[0].other)*100}%`}} className="bg-[#bd7140]"/><div style={{width:`${row.other/Math.max(1,issueMix[0].resident+issueMix[0].other)*100}%`}} className="bg-[#71859d]"/></div><span className="tabular-nums sm:text-right">{row.resident} / {row.other}</span></div>)}</div><p className="text-sm text-neutral-600 mt-4">The two numbers are resident reports / other city reports. Austin’s source categories describe who sent the report; they do not validate the event or establish fault.</p></div>
      <details className="viz-card p-5 mt-3"><summary className="cursor-pointer font-semibold text-[#184f95]">Recent Austin Resident Reports ({feedback.length} total)</summary><div className="grid gap-2 mt-4">{[...feedback].reverse().slice(0,20).map(row=><div key={row.id} className="text-sm border-t border-[#e1e7ee] pt-2 flex justify-between gap-4"><span>{row.reported_date} · {row.issue} · {row.operator}</span><a href={row.source_url} className="text-[#184f95] underline whitespace-nowrap">{row.id} ↗</a></div>)}</div></details>
      <details className="viz-card p-5 mt-3"><summary className="cursor-pointer font-semibold text-[#184f95]">Other City Reports by Source ({austin.total_city_reports-austin.resident_feedback_count})</summary><Bars rows={austin.reporter_types.filter(r=>r.type.toLowerCase()!=="resident feedback").map(r=>({label:r.type,value:r.reports}))} color="#7b8da0" /></details>
      <details className="viz-card p-5 mt-3"><summary className="cursor-pointer font-semibold text-[#184f95]">Recent Reports From Other City Sources</summary><div className="grid gap-2 mt-4">{[...staffReports].reverse().slice(0,20).map(row=><div key={row.id} className="text-sm border-t border-[#e1e7ee] pt-2 flex justify-between gap-4"><span>{row.reported_date} · {row.reporter_type} · {row.issue} · {row.operator}</span><a href={row.source_url} className="text-[#184f95] underline whitespace-nowrap">{row.id} ↗</a></div>)}</div></details>
      <p className="text-sm text-neutral-600 mt-3">{austin.limitations} Most recent incident date: {austin.latest_reported_date}.</p>
    </section>
    <details className="mt-9"><summary className="cursor-pointer text-lg font-semibold text-[#184f95]">Coverage in Other Deployment Markets</summary><p className="text-sm text-neutral-600 mt-2">Missing public AV-identifiable data are coverage gaps, not zero complaints.</p><div className="grid sm:grid-cols-2 gap-3 mt-3">{coverage.states.filter(row=>!['indexed','indexed_resident_feedback'].includes(row.status)).map((row,i)=><article key={row.state+i} className="viz-card p-4"><strong>{row.state} · {row.markets.join(", ")}</strong><p className="text-sm text-neutral-600 mt-2">{row.note}</p><a href={row.source_url} className="text-sm text-[#184f95] underline">Official Source ↗</a></article>)}</div></details>
    <div className="flex flex-wrap gap-4 text-sm mt-7 text-[#184f95] underline"><a href={`${base}/data/av_311_complaints.csv`}>SF Requests CSV ↗</a><a href={`${base}/data/av_311_complaints.json`}>SF JSON ↗</a><a href={`${base}/data/austin_av_reports.csv`}>Austin Reports CSV ↗</a><a href={`${base}/data/austin_av_reports.json`}>Austin JSON ↗</a><a href={`${base}/data/av_311_source_registry.json`}>Coverage Registry ↗</a></div>
  </main>;
}
