import complaints from "../../../public/data/av_311_complaints.json";
import coverage from "../../../public/data/av_311_source_registry.json";

const DATA_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const monthly = complaints.monthly.slice(-12);
const max = Math.max(...monthly.map(row => row.complaints));
const byType = Object.entries(complaints.records.reduce((acc: Record<string, number>, row) => {
  const label = row.type === "incident_report" ? "Incident Report" : row.type === "general_complaint" ? "General Complaint" : "Other Feedback";
  acc[label] = (acc[label] ?? 0) + 1; return acc;
}, {})).sort((a, b) => b[1] - a[1]);

export default function ComplaintsPage() {
  return <main className="max-w-6xl px-8 py-8"><p className="eyebrow">Reporting / Municipal 311</p><h1 className="text-4xl font-semibold text-[#0b1d33] mt-2">AV 311 Complaints</h1>
    <p className="text-base leading-relaxed text-neutral-600 mt-3 max-w-4xl">A growing index of public 311 requests explicitly classified as autonomous vehicle complaints. The current count covers <strong>San Francisco only</strong>. We are tracking data availability in every state with a documented AV deployment; markets without usable AV identifiers are marked as coverage gaps, not zero complaints.</p>
    <div className="grid sm:grid-cols-3 gap-3 mt-6"><div className="viz-card p-5"><p className="text-sm text-neutral-600">Indexed AV 311 Requests</p><strong className="block text-3xl text-[#123b69] mt-2">{complaints.total_records.toLocaleString()}</strong><p className="text-sm text-neutral-600">San Francisco · since April 2025</p></div><div className="viz-card p-5"><p className="text-sm text-neutral-600">Markets With AV-Identifiable Data</p><strong className="block text-3xl text-[#123b69] mt-2">{complaints.markets.length}</strong><p className="text-sm text-neutral-600">Of 11 deployment states reviewed</p></div><div className="viz-card p-5"><p className="text-sm text-neutral-600">Latest Source Update</p><strong className="block text-2xl text-[#123b69] mt-2">{complaints.source_data_as_of.slice(0, 10)}</strong><p className="text-sm text-neutral-600">San Francisco open data timestamp</p></div></div>
    <div className="grid lg:grid-cols-2 gap-3 mt-6"><section className="viz-card p-5"><h2 className="text-xl font-semibold">Requests by Month</h2><p className="text-sm text-neutral-600">San Francisco · most recent 12 months</p><div className="grid gap-2 mt-5">{monthly.map(row => <div key={row.month} className="grid grid-cols-[75px_1fr_42px] items-center gap-2 text-sm"><span className="text-neutral-600">{row.month}</span><div className="h-4 bg-[#e8eef4] rounded-sm"><div className="h-4 bg-[#2c76bf] rounded-sm" style={{ width: (100 * row.complaints / max) + "%" }} /></div><span className="text-right tabular-nums">{row.complaints}</span></div>)}</div></section>
      <section className="viz-card p-5"><h2 className="text-xl font-semibold">City Classification</h2><p className="text-sm text-neutral-600">The request subtype records how SF311 categorized a submission.</p><div className="grid gap-4 mt-6">{byType.map(([name, count]) => <div key={name}><div className="flex justify-between text-sm"><span>{name}</span><strong>{count.toLocaleString()}</strong></div><div className="h-3 bg-[#e8eef4] mt-1 rounded-sm"><div className="h-3 bg-[#2c76bf] rounded-sm" style={{ width: (100 * count / complaints.total_records) + "%" }} /></div></div>)}</div><p className="text-sm text-neutral-600 mt-5">A submission classified as “Incident Report” is still a public 311 request; it is not a verified collision or an NHTSA crash report.</p></section></div>
    <section className="viz-card p-5 mt-4"><h2 className="text-xl font-semibold">Market Breakdown</h2><p className="text-sm text-neutral-600 mt-1">Only markets with a validated, AV-identifiable public 311 feed contribute to the total.</p><div className="grid sm:grid-cols-3 gap-3 mt-4">{complaints.markets.map(market => <div key={market.market} className="rounded-lg border border-[#dce5ec] p-4"><p className="font-semibold">{market.market}, {market.state}</p><strong className="text-2xl text-[#123b69] block mt-2">{market.complaints.toLocaleString()}</strong><span className="text-sm text-neutral-600">AV-category requests</span></div>)}</div></section>
    <section className="mt-7"><h2 className="text-xl font-semibold">Recent Requests</h2><p className="text-sm text-neutral-600 mt-1">Publicly indexed record metadata. Source links open the corresponding official 311 API record.</p><div className="grid gap-2 mt-3">{[...complaints.records].reverse().slice(0, 20).map(row => <div key={row.id} className="viz-card px-4 py-3 flex flex-wrap gap-2 items-center justify-between"><span className="text-sm"><strong>{row.market}</strong> · {row.requested_date} · {row.type.replaceAll("_", " ")} · {row.status}</span><a href={row.source_url} className="text-sm text-[#184f95] underline">{row.id} ↗</a></div>)}</div></section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Deployment State Coverage</h2><p className="text-sm text-neutral-600 mt-1">Municipal 311 feeds differ in coverage and public fields. “Review Needed” and “Source Reviewed” do not mean no complaints occurred.</p><div className="grid sm:grid-cols-2 gap-3 mt-4">{coverage.states.map((row, i) => <article key={row.state + i} className="viz-card p-4"><div className="flex flex-wrap gap-2 justify-between items-center"><strong>{row.state} · {row.markets.join(", ")}</strong><span className="text-xs uppercase font-semibold text-[#184f95]">{row.status.replaceAll("_", " ")}</span></div><p className="text-sm text-neutral-600 mt-2">{row.note}</p><a href={row.source_url} className="text-sm text-[#184f95] underline inline-block mt-2">Official source ↗</a></article>)}</div></section>
    <p className="text-sm text-neutral-600 leading-relaxed mt-7 max-w-4xl"><strong>How to read this:</strong> {complaints.limitations} Source matches the exact SF311 “Autonomous Vehicle Complaints” category; public fields do not reliably identify Waymo or another operator. Avoid comparing raw counts across cities with different 311 systems.</p>
    <div className="flex flex-wrap gap-4 text-sm mt-3"><a href={complaints.source_url} className="text-[#184f95] underline">San Francisco source ↗</a><a href={`${DATA_PATH}/data/av_311_complaints.csv`} className="text-[#184f95] underline">Download records CSV ↗</a><a href={`${DATA_PATH}/data/av_311_complaints.json`} className="text-[#184f95] underline">Download JSON ↗</a><a href={`${DATA_PATH}/data/av_311_source_registry.json`} className="text-[#184f95] underline">Coverage registry JSON ↗</a></div>
  </main>;
}
