import { promises as fs } from "fs";
import path from "path";
import Link from "next/link";
import { CompanyDeploymentExplorer, type Location, type Geojson, type S2Geojson, type VintageSummary } from "@/components/CompanyDeploymentExplorer";
import type { ActivityMonthlyDataset } from "@/lib/activity";
async function load<T>(name:string):Promise<T>{return JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data",name),"utf8"));}
type Month = { year:number; month:number; miles:number };
function MonthlyTrend({months}:{months:Month[]}){
  const max=Math.max(...months.map(r=>r.miles));
  const x=(i:number)=>36+i*(520/(months.length-1));
  const y=(miles:number)=>145-miles/max*115;
  const label=(r:Month)=>`${r.year}-${String(r.month).padStart(2,"0")}`;
  const points=months.map((r,i)=>`${x(i)},${y(r.miles)}`).join(" ");
  return <section className="viz-card p-5 mt-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">CPUC Monthly Trip Reporting · California</p><h2 className="text-xl font-semibold mt-2">Waymo Miles per Month</h2></div><span className="text-sm text-neutral-600">P1 + P2 + P3 · millions of miles</span></div><svg viewBox="0 0 580 185" role="img" aria-label={`Waymo California monthly VMT from ${label(months[0])} to ${label(months.at(-1)!)}; latest ${Math.round(months.at(-1)!.miles).toLocaleString()} miles`} className="w-full h-auto mt-3"><path d="M36 145H556M36 88H556M36 30H556" stroke="#dce5ec"/><text x="30" y="33" textAnchor="end" fill="#536273" fontSize="10">{(max/1e6).toFixed(0)}M</text><text x="30" y="147" textAnchor="end" fill="#536273" fontSize="10">0</text><polyline points={points} fill="none" stroke="#2166a8" strokeWidth="3" strokeLinejoin="round"/>{months.map((r,i)=><g key={label(r)}><circle cx={x(i)} cy={y(r.miles)} r="2.8" fill="#2166a8"><title>{label(r)} · {Math.round(r.miles).toLocaleString()} miles</title></circle>{(i===0 || i===months.length-1 || (i%6===0 && i<months.length-3)) && <text x={x(i)} y="172" fill="#536273" fontSize="10" textAnchor="middle">{label(r)}</text>}</g>)}</svg><p className="text-sm text-neutral-600 mt-1">California driverless passenger service mileage, including unoccupied miles. CPUC publishes monthly records in quarterly updates. This series has a different scope from the S2 mileage map below. <Link href="/activity" className="underline text-[#184f95]">Explore Trip Reporting →</Link></p></section>;
}
export default async function WaymoActivityPage(){
  const [operations,shapes,cells,vintages,cpuc]=await Promise.all([load<{locations:Location[]}>("operational_domains.json"),load<Geojson>("odd_current_geometries.geojson"),load<S2Geojson>("waymo_s2_latest.geojson"),load<VintageSummary>("waymo_s2_vintage_summary.json"),load<ActivityMonthlyDataset>("cpuc_activity_monthly.json")]);
  const total=cells.features.reduce((sum,f)=>sum+Number(f.properties.waymo_ro_miles || 0),0);
  const months=cpuc.data.filter(r=>r.operator_tcpid === "PSG0038152" && r.program === "driverless" && r.total_vmt_period1 != null && r.total_vmt_period2 != null && r.total_vmt_period3 != null).map(r=>({year:r.calendar_year,month:r.calendar_month,miles:r.total_vmt_period1!+r.total_vmt_period2!+r.total_vmt_period3!})).sort((a,b)=>a.year-b.year||a.month-b.month);
  return <main className="max-w-7xl px-8 py-8"><p className="eyebrow">Operations / Waymo Activity</p><h1 className="text-4xl font-semibold text-[#0b1d33] mt-3">Where Waymo Drives</h1><p className="text-base leading-relaxed text-neutral-600 mt-3 max-w-3xl">Explore Waymo-reported operational miles by S2 cell and release. Choose a city to inspect the observed mileage footprint. Where S2 mileage is unavailable, the map shows a sourced service boundary or documented market point.</p><div className="grid sm:grid-cols-3 gap-3 mt-6">{[["Published S2 Cells",cells.features.length.toLocaleString()],["Miles in Latest S2 Release",Math.round(total).toLocaleString()],["Latest Release",`${vintages.latest_vintage.slice(0,4)}–${vintages.latest_vintage.slice(4)}`]].map(([label,value])=><div className="viz-card p-5" key={label}><p className="text-sm text-neutral-600">{label}</p><strong className="block mt-2 text-2xl text-[#123b69]">{value}</strong></div>)}</div><p className="mt-4 text-sm text-neutral-600">S2 mileage includes non-passenger operations and does not establish an official service boundary. Northern and Southern California reporting areas are analytical groupings. <Link href="/manufacturers" className="underline text-[#184f95]">Compare manufacturers →</Link></p>{months.length>1 && <MonthlyTrend months={months} />}<div className="mt-6"><CompanyDeploymentExplorer waymoOnly locations={operations.locations} geometries={shapes} latestS2={cells} vintages={vintages} /></div><a href={`${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/data/waymo_s2_latest.geojson`} className="inline-block mt-5 text-sm text-[#184f95] underline">Download S2 GeoJSON ↗</a></main>;
}
