import { promises as fs } from "fs";
import path from "path";
import Link from "next/link";
import { CompanyDeploymentExplorer, type Location, type Geojson, type S2Geojson, type VintageSummary } from "@/components/CompanyDeploymentExplorer";
async function load<T>(name:string):Promise<T>{return JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data",name),"utf8"));}
type Release = {vintage_end:string; cumulative_miles:number};
function ReleaseTrend({releases}:{releases:Release[]}){
  const max=Math.max(...releases.map(r=>r.cumulative_miles));
  const points=releases.map((r,i)=>`${28+i*(524/(releases.length-1))},${150-r.cumulative_miles/max*118}`).join(" ");
  return <section className="viz-card p-5 mt-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">Published Release History</p><h2 className="text-xl font-semibold mt-2">Waymo-Reported Operational Miles</h2></div><span className="text-sm text-neutral-600">Cumulative · millions of miles</span></div><svg viewBox="0 0 580 185" role="img" aria-label={`Operational miles rose from ${Math.round(releases[0].cumulative_miles/1e6)} million in the first indexed release to ${Math.round(max/1e6)} million in the latest release`} className="w-full h-auto mt-3"><path d="M28 150H555" stroke="#cbd7e1"/><path d="M28 88H555" stroke="#e2e9ef"/><path d="M28 32H555" stroke="#e2e9ef"/><polyline points={points} fill="none" stroke="#2166a8" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{releases.map((r,i)=><g key={r.vintage_end}><circle cx={28+i*(524/(releases.length-1))} cy={150-r.cumulative_miles/max*118} r="4" fill="#2166a8"/><text x={28+i*(524/(releases.length-1))} y="176" fontSize="10" fill="#536273" textAnchor="middle">{r.vintage_end.slice(0,4)}–{r.vintage_end.slice(4)}</text></g>)}</svg><p className="text-sm text-neutral-600 mt-1">Cumulative operational mileage, including miles without a passenger. Select a release below to inspect its S2 cells.</p></section>;
}
export default async function WaymoActivityPage(){
  const [operations,shapes,cells,vintages]=await Promise.all([load<{locations:Location[]}>("operational_domains.json"),load<Geojson>("odd_current_geometries.geojson"),load<S2Geojson>("waymo_s2_latest.geojson"),load<VintageSummary>("waymo_s2_vintage_summary.json")]);
  const total=cells.features.reduce((sum,f)=>sum+Number(f.properties.waymo_ro_miles || 0),0);
  return <main className="max-w-7xl px-8 py-8"><p className="eyebrow">Operations / Waymo Activity</p><h1 className="text-4xl font-semibold text-[#0b1d33] mt-3">Where Waymo Drives</h1><p className="text-base leading-relaxed text-neutral-600 mt-3 max-w-3xl">Explore Waymo-reported operational miles by S2 cell and release. Choose a city to inspect the observed mileage footprint. Where S2 mileage is unavailable, the map shows a sourced service boundary or documented market point.</p><div className="grid sm:grid-cols-3 gap-3 mt-6">{[["Published S2 Cells",cells.features.length.toLocaleString()],["Miles in Latest S2 Release",Math.round(total).toLocaleString()],["Latest Release",`${vintages.latest_vintage.slice(0,4)}–${vintages.latest_vintage.slice(4)}`]].map(([label,value])=><div className="viz-card p-5" key={label}><p className="text-sm text-neutral-600">{label}</p><strong className="block mt-2 text-2xl text-[#123b69]">{value}</strong></div>)}</div><p className="mt-4 text-sm text-neutral-600">S2 mileage includes non-passenger operations and does not establish an official service boundary. Northern and Southern California reporting areas are analytical groupings. <Link href="/manufacturers" className="underline text-[#184f95]">Compare manufacturers →</Link></p><ReleaseTrend releases={vintages.vintages as Release[]} /><div className="mt-6"><CompanyDeploymentExplorer waymoOnly locations={operations.locations} geometries={shapes} latestS2={cells} vintages={vintages} /></div><a href={`${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/data/waymo_s2_latest.geojson`} className="inline-block mt-5 text-sm text-[#184f95] underline">Download S2 GeoJSON ↗</a></main>;
}
