import { promises as fs } from "fs";
import path from "path";
import Link from "next/link";
import { WaymoMileageOverview } from "@/components/WaymoMileageOverview";
import type { S2Geojson } from "@/components/CompanyDeploymentExplorer";
async function load<T>(name:string):Promise<T>{return JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data",name),"utf8"));}
export default async function WaymoActivityPage(){
  const [cells,vintages]=await Promise.all([load<S2Geojson>("waymo_s2_latest.geojson"),load<{latest_vintage:string;vintages:{vintage_end:string;cumulative_miles:number}[]}>("waymo_s2_vintage_summary.json")]);
  const total=cells.features.reduce((sum,f)=>sum+Number(f.properties.waymo_ro_miles||0),0);
  const uniqueCells=new Set(cells.features.map(f=>f.properties.s2_cell)).size;
  const base=process.env.NEXT_PUBLIC_BASE_PATH ?? "";
  return <main className="max-w-7xl px-5 sm:px-8 py-8"><p className="eyebrow">Operations / Waymo Activity</p><h1 className="text-4xl font-semibold text-[#0b1d33] mt-3">Where Waymo Drives</h1><p className="text-base leading-relaxed text-neutral-600 mt-3 max-w-3xl">Explore nationally reported cumulative S2 mileage by release and market, then inspect the original interactive visualization below.</p><div className="grid sm:grid-cols-3 gap-3 mt-6">{[["Published S2 Cells",uniqueCells.toLocaleString()],["Cumulative Miles in Latest Release",Math.round(total).toLocaleString()],["Latest Release",`${vintages.latest_vintage.slice(0,4)}–${vintages.latest_vintage.slice(4)}`]].map(([label,value])=><div className="viz-card p-5" key={label}><p className="text-sm text-neutral-600">{label}</p><strong className="block mt-2 text-2xl text-[#123b69]">{value}</strong></div>)}</div><p className="mt-4 text-sm text-neutral-600">Waymo’s S2 releases show cumulative operational mileage, including travel without passengers. They cover published cells and do not define a service boundary. Market groupings are analytical.</p><WaymoMileageOverview vintages={vintages.vintages} cells={cells} /><section className="mt-7"><div className="flex items-center justify-between gap-3 flex-wrap"><h2 className="text-2xl font-semibold">Explore S2 Cells</h2><a className="text-sm text-[#184f95] underline" href="https://waymovmt.netlify.app/" target="_blank" rel="noopener noreferrer">Open Original Map ↗</a></div><iframe className="mt-4 w-full rounded-xl border border-[#cad8e8]" style={{height:"min(82vh,900px)",minHeight:550}} src="https://waymovmt.netlify.app/" title="Original Waymo S2 VMT interactive map" loading="lazy" /></section><div className="flex gap-6 flex-wrap mt-5 text-sm text-[#184f95] underline"><a href={`${base}/data/waymo_s2_explorer.csv`}>Download Map CSV ↗</a><a href={`${base}/data/waymo_s2_latest.geojson`}>Download S2 GeoJSON ↗</a><Link href="/manufacturers">Compare Manufacturers →</Link></div></main>;
}
