"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { OddMap, type OddPoint, type OddPolygon } from "@/components/OddMap";
import { CityBackdrop } from "@/components/CityBackdrop";
import type { Location, Geojson } from "@/components/CompanyDeploymentExplorer";
import type { CompanyProfile } from "@/lib/manufacturers";

const freight = new Set(["Aurora","Gatik","Kodiak AI","PlusAI","Torc","Waabi"]);
const domains: Record<string,string> = {Waymo:"waymo.com",Zoox:"zoox.com",Tesla:"tesla.com",Motional:"motional.com",Avride:"avride.ai",Beep:"ridebeep.com","May Mobility":"maymobility.com",Aurora:"aurora.tech",Gatik:"gatik.ai","Kodiak AI":"kodiak.ai",Waabi:"waabi.ai",Nuro:"nuro.ai",WeRide:"weride.ai",Mobileye:"mobileye.com",PlusAI:"plus.ai",Torc:"torc.ai"};
const phase = (row: Location) => row.activity_type ?? row.phase;
const isCurrent = (row: Location) => (row.evidence_status ?? "current") === "current" && ["testing","deployment"].includes(phase(row)) && !/planned|permit|authorized/i.test(row.status);
const id = (market: string, state: string) => `${market.replace(/\s*\(I-\d+\)$/, "")}|${state}`;

export function ManufacturerTracker({ locations, geometries, profiles }: {locations:Location[]; geometries:Geojson; profiles:CompanyProfile[]}) {
  const companies = useMemo(() => [...new Set([...locations.filter(isCurrent).map(x=>x.company),...geometries.features.filter(f=>f.properties?.evidence_status === "current").map(f=>String(f.properties?.company ?? ""))])].filter(Boolean).sort((a,b)=>a === "Waymo" ? -1 : b === "Waymo" ? 1 : a.localeCompare(b)), [locations,geometries]);
  const [company, setCompany] = useState("Waymo");
  const [city, setCity] = useState("");
  const selected = companies.includes(company) ? company : companies[0];
  const profile = profiles.find(p=>p.name === selected);
  const records = locations.filter(x=>x.company === selected && isCurrent(x));
  const features = geometries.features.filter(f=>{const p=f.properties ?? {};return p.company === selected && p.evidence_status === "current" && ["testing","deployment"].includes(String(p.activity_type ?? p.phase)) && p.geometry_precision !== "schematic_endpoints_not_exact_route" && p.geometry_basis !== "route_corridor_endpoint_connection";});
  const markets = [...new Map([...records.map(x=>({market:x.market,state:x.state,phase:phase(x)})),...features.map(f=>({market:String(f.properties?.market ?? ""),state:String(f.properties?.state ?? ""),phase:String(f.properties?.activity_type ?? f.properties?.phase ?? "deployment")}))].filter(x=>x.market && x.state).map(x=>[id(x.market,x.state),x] as const))].map(([,x])=>x).sort((a,b)=>a.market.localeCompare(b.market));
  const active = markets.find(m=>id(m.market,m.state)===city) ?? markets.find(m=>id(m.market,m.state)==="San Francisco Bay Area|CA") ?? markets[0];
  const visible = records.filter(x=>active && id(x.market,x.state)===id(active.market,active.state));
  const polygons:OddPolygon[] = features.filter(f=>active && id(String(f.properties?.market),String(f.properties?.state))===id(active.market,active.state)).map(f=>({feature:f,company:selected,market:String(f.properties?.market ?? ""),state:String(f.properties?.state ?? ""),phase:String(f.properties?.activity_type ?? f.properties?.phase ?? "deployment"),event_date:String(f.properties?.event_date ?? ""),geometry_ref:String(f.properties?.geometry_basis ?? ""),geometry_type:f.geometry.type,source_url:String(f.properties?.source_url ?? "")}));
  const covered = new Set(polygons.filter(x=>!x.geometry_type?.includes("LineString")).map(x=>id(x.market,x.state)+"|"+x.phase));
  const points:OddPoint[] = visible.filter(x=>x.lat!=null && x.lon!=null && !covered.has(id(x.market,x.state)+"|"+phase(x))).map(x=>({company:selected,market:x.market,state:x.state,lat:x.lat!,lon:x.lon!,phase:phase(x),status:x.status,mode:x.mode}));
  const evidence = visible[0]?.source_url ?? polygons[0]?.source_url;
  return <div className="mt-6"><section className="viz-card p-5"><h2 className="text-xl font-semibold">Select a Manufacturer</h2><p className="text-sm text-neutral-600 mt-1">Select a company to see its approach, partnerships, and documented testing or deployment.</p>{[["Passenger, Delivery and Shuttle",companies.filter(n=>!freight.has(n))],["Autonomous Trucking",companies.filter(n=>freight.has(n))]].map(([label,names])=><div key={String(label)} className="mt-5"><h3 className="text-xs uppercase tracking-wider font-bold text-neutral-500">{label}</h3><div className="flex flex-wrap gap-2 mt-2">{(names as string[]).map(name=><button key={name} type="button" onClick={()=>{setCompany(name);setCity("");}} aria-pressed={selected === name} className={`inline-flex gap-2 items-center rounded-md px-3 py-2 border text-sm font-semibold ${selected === name ? "bg-[#e7f1fb] border-[#123b69] text-[#123b69]" : "bg-white border-neutral-200 text-neutral-700 hover:border-[#7ca7d0]"}`}>{domains[name] && <img src={`https://www.google.com/s2/favicons?domain=${domains[name]}&sz=64`} alt="" className="w-6 h-6 object-contain"/>}{name}</button>)}</div></div>)}</section>
    <section className="viz-card p-6 mt-4" aria-live="polite"><div className="flex flex-wrap justify-between gap-4"><div><p className="eyebrow">Operator Profile</p><h2 className="text-3xl font-semibold mt-2 text-[#0b1d33]">{selected}</h2><p className="mt-2 text-neutral-700">{profile?.service ?? "Documented current U.S. AV activity."}</p></div>{profile && <Link href={`/manufacturers/${profile.slug}/developments`} className="self-start rounded-md bg-[#123b69] text-white px-4 py-2 text-sm font-semibold">Company Developments →</Link>}</div><div className="grid md:grid-cols-2 gap-6 mt-5 pt-5 border-t border-neutral-200"><div><h3 className="font-semibold">Approach</h3><p className="text-sm leading-relaxed text-neutral-700 mt-2">{profile?.approach ?? "Activity is documented by the linked location record; a fuller operator profile is under review."}</p></div><div><h3 className="font-semibold">Partnerships</h3><p className="text-sm leading-relaxed text-neutral-700 mt-2">{profile?.partnerships ?? "No reviewed partnership description is indexed yet."}</p></div></div></section>
    <div className="grid lg:grid-cols-[260px_minmax(0,1fr)] gap-4 items-start mt-4"><aside className="viz-card p-4"><h2 className="text-lg font-semibold">Documented Locations <span className="text-neutral-500 text-sm">({markets.length})</span></h2><div className="max-h-[580px] overflow-y-auto space-y-2 mt-4">{markets.map(m=><button type="button" key={id(m.market,m.state)} aria-pressed={id(m.market,m.state)===id(active?.market ?? "",active?.state ?? "")} onClick={()=>setCity(id(m.market,m.state))} className={`relative overflow-hidden w-full min-h-20 text-left flex gap-2 items-center rounded-lg p-3 border ${id(m.market,m.state)===id(active?.market ?? "",active?.state ?? "") ? "border-[#7fa9d0] bg-[#edf5fb]" : "border-neutral-200 hover:border-[#7fa9d0]"}`}><CityBackdrop market={m.market}/><span className="relative z-10"><strong className="block text-sm leading-tight">{m.market}</strong><small className="text-neutral-600">{m.state} · {m.phase === "testing" ? "Testing" : "Deployment"}</small></span></button>)}</div></aside><section className="viz-card p-5 min-w-0"><p className="eyebrow">{selected} / Documented Geography</p><h2 className="text-xl font-semibold mt-2">{active ? `${active.market}, ${active.state}` : "No mapped location"}</h2><p className="mt-2 text-sm text-neutral-600">Mapped service areas and corridors appear where a sourced geometry exists. Points show documented activity where a precise boundary is unavailable. Blue indicates deployment; amber indicates testing.</p><div className="mt-4"><OddMap key={`${selected}|${active?.market}`} polygons={polygons} points={points} s2Features={[]} /></div>{evidence && <a href={evidence} target="_blank" rel="noreferrer" className="inline-block mt-3 text-sm underline text-[#184f95]">Activity Source ↗</a>}{selected === "Waymo" && <p className="mt-4 text-sm text-neutral-600">Explore the separate <Link className="underline text-[#184f95]" href="/waymo-activity">Waymo Activity tracker</Link> for S2 cell mileage and release comparisons.</p>}</section></div>
  </div>;
}
