"use client";
import { useRef, useState } from "react";

export type SeriousCrash = { incident_key:string; incident_date:string; city:string; state:string; reporting_entities:string; report_ids:string; severity:string; make:string; model:string; crash_with:string; roadway_type:string; engagement_status:string; air_bag_deployment:string; source_url:string };
export type MediaContext = { report_id:string; match:string; narrative:string; attribution:string; sources:string[] };
export type ReviewedSource = { url:string; title:string; related_report_id:string|null; status:string; finding:string };

function month(raw:string) {
  const [m,y]=raw.split("-");
  const index=["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"].indexOf(m.toUpperCase());
  return index<0?raw:new Date(Date.UTC(Number(y),index,1)).toLocaleString("en-US",{month:"short",year:"numeric",timeZone:"UTC"});
}

export function SgoSeriousCrashList({crashes,media,reviewedSources}:{crashes:SeriousCrash[];media:MediaContext[];reviewedSources:ReviewedSource[]}) {
  const [selected,setSelected]=useState(crashes[0]?.incident_key??"");
  const rail=useRef<HTMLDivElement>(null);
  const crash=crashes.find(c=>c.incident_key===selected)??crashes[0];
  if(!crash) return null;
  const fatal=crashes.filter(c=>c.severity.startsWith("Fatal")).length;
  const context=media.find(m=>crash.report_ids.split(";").map(id=>id.trim()).includes(m.report_id));
  return <section className="mt-7" aria-label="Serious or Fatal Crash Timeline">
    <div className="flex flex-wrap justify-between items-end gap-3"><div><p className="eyebrow">NHTSA SGO · Latest Report Versions</p><h2 className="text-xl font-semibold tracking-tight mt-2">Serious or Fatal Crashes</h2></div><span className="text-sm text-neutral-600">{crashes.length} Distinct Reported Incidents</span></div>
    <p className="text-sm text-neutral-600 mt-2 max-w-4xl">Each marker is one reported crash. Select a month and city for the filing details and any matched media account. SGO injury severity is reported or alleged; it does not establish fault or the final medical outcome. NHTSA supplies a month, not an exact crash date, in this public list. The latest release includes part of August 2026.</p>
    <div className="grid grid-cols-3 gap-2.5 mt-4">{[[crashes.length,"Reported Incidents"],[fatal,"Fatalities Alleged"],[crashes.length-fatal,"Serious Injuries Alleged"]].map(([value,label])=><div key={label} className="viz-card p-3 sm:p-4"><strong className="block text-2xl sm:text-3xl text-[#123b69] tabular-nums">{value}</strong><span className="text-sm text-neutral-600">{label}</span></div>)}</div>
    <div className="flex items-center justify-between mt-5 mb-2"><p className="text-sm font-semibold text-[#152b45]">Crash Timeline · Newest First</p><div className="flex gap-2"><button type="button" className="border border-[#cbd9e8] rounded px-3 py-1 text-[#123b69]" aria-label="Scroll toward newer reports" onClick={()=>rail.current?.scrollBy({left:-500,behavior:"smooth"})}>←</button><button type="button" className="border border-[#cbd9e8] rounded px-3 py-1 text-[#123b69]" aria-label="Scroll toward older reports" onClick={()=>rail.current?.scrollBy({left:500,behavior:"smooth"})}>→</button></div></div>
    <div ref={rail} className="overflow-x-auto pb-3" role="group" aria-label="Select a crash by month and city"><div className="flex min-w-max border-t-2 border-[#dce5ec] pt-4 gap-2.5">{crashes.map(item=>{const death=item.severity.startsWith("Fatal");return <button type="button" key={item.incident_key} aria-pressed={item.incident_key===crash.incident_key} onClick={()=>setSelected(item.incident_key)} className={`relative w-48 sm:w-52 shrink-0 text-left rounded-lg border p-3.5 transition-colors ${item.incident_key===crash.incident_key?"border-[#173d65] bg-[#e8f2fb] shadow-sm":"border-[#dce5ec] bg-white hover:bg-[#f4f8fc]"}`}>
      <span className={`absolute -top-[23px] left-5 h-3 w-3 rounded-full border-2 border-white ${death?"bg-[#b44343]":"bg-[#d69138]"}`} aria-hidden="true"/><span className="block text-sm font-semibold text-[#123b69]">{month(item.incident_date)}</span><span className="block mt-1 font-semibold text-[#152b45] leading-tight">{item.city}, {item.state}</span><span className="block text-sm text-neutral-600 mt-1">{item.reporting_entities.split(";")[0]}</span><span className={`inline-block text-xs font-semibold mt-2 ${death?"text-[#a43c3c]":"text-[#98601d]"}`}>{death?"Fatality Alleged":"Serious Injury Alleged"}</span>
    </button>})}</div></div>
    <article className="viz-card p-4 sm:p-5 mt-2" aria-live="polite" aria-label="Selected Crash Details"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="eyebrow">Selected Crash · {month(crash.incident_date)}</p><h3 className="text-xl font-semibold text-[#152b45] mt-1">{crash.city}, {crash.state} · {crash.reporting_entities}</h3></div><span className={`text-sm font-semibold ${crash.severity.startsWith("Fatal")?"text-[#a43c3c]":"text-[#98601d]"}`}>{crash.severity}</span></div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-3 text-sm mt-4 pt-4 border-t border-[#dce5ec]"><div><span className="block text-neutral-500">Reported Collision With</span>{crash.crash_with||"Not Reported"}</div><div><span className="block text-neutral-500">Roadway</span>{crash.roadway_type||"Not Reported"}</div><div><span className="block text-neutral-500">Subject Vehicle</span>{[crash.make,crash.model].filter(Boolean).join(" ")||"Not Reported"}</div><div><span className="block text-neutral-500">Air Bags</span>{crash.air_bag_deployment}</div><div><span className="block text-neutral-500">Automation System</span>{crash.engagement_status||"Not Reported"}</div><div><span className="block text-neutral-500">NHTSA Report IDs</span>{crash.report_ids}</div></div>
      {context?<div className="bg-[#f1f6fb] rounded p-4 mt-4"><strong className="text-sm text-[#123b69]">{context.match.includes("agency_context_only")?"Agency Context":"Narrative Developed From Media and Agency Reports"}</strong><p className="text-sm leading-relaxed mt-2">{context.narrative}</p><p className="text-sm text-neutral-600 mt-2">{context.attribution} · <strong>{context.match.startsWith("exact_")?"Matched by NHTSA Report ID":context.match.startsWith("probable_")?"Probable Match; Report ID Not Cited by Media":"Matched by Event Details; Report ID Not Cited by Media"}</strong></p><div className="flex flex-wrap gap-3 mt-2">{context.sources.map((url,j)=><a key={url} href={url} className="text-sm text-[#184f95] underline">Source {j+1} ↗</a>)}</div></div>:<p className="text-sm text-neutral-600 mt-4">No independently matched media account has been verified for this report. The SGO fields above do not provide a complete account of the crash.</p>}
      {reviewedSources.filter(row=>row.related_report_id&&crash.report_ids.includes(row.related_report_id)).map(row=><p key={row.url} className="text-sm text-neutral-600 mt-4 border-l-4 border-[#d6ac66] pl-3"><strong>Related Article · Match Unverified:</strong> {row.finding} <a href={row.url} className="text-[#184f95] underline">Review Article ↗</a></p>)}
      <p className="text-sm text-neutral-600 mt-4">Fields come from the latest incident submissions. For the filing narrative and updates, find the Report IDs in the <a className="text-[#184f95] underline" href={crash.source_url}>NHTSA Source CSV ↗</a>.</p>
    </article>
    <div className="flex flex-wrap gap-4 mt-4"><a href={`${process.env.NEXT_PUBLIC_BASE_PATH??""}/data/sgo_serious_fatal_crashes.csv`} download className="text-sm text-[#184f95] underline">Download Serious and Fatal Crash List CSV ↗</a><a href={`${process.env.NEXT_PUBLIC_BASE_PATH??""}/data/sgo_media_context.json`} className="text-sm text-[#184f95] underline">Download Media Context JSON ↗</a></div>
    <details className="mt-5 text-sm text-neutral-600"><summary className="cursor-pointer text-[#184f95] font-semibold">Articles Reviewed but Not Linked to an SGO Crash</summary><div className="grid gap-3 mt-3">{reviewedSources.filter(row=>!row.related_report_id).map(row=><p key={row.url}><strong>{row.title}.</strong> {row.finding} <a href={row.url} className="text-[#184f95] underline">Read Source ↗</a></p>)}</div></details>
  </section>;
}
